apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: ecr-image
      imagePullSecrets:
        - name: my-docker-credentials
