apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-blue
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: petclinic-bg
        version: updatethis
    spec:
      containers:
        - name: petclinic
          image: ecr-image
      imagePullSecrets:
        - name: my-docker-credentials
