apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-bluegreen-update-version
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: petclinic-bg
        version: update-version
    spec:
      containers:
        - name: petclinic
          image: ecr-image
      imagePullSecrets:
        - name: my-docker-credentials
