apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-bluegreen
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    name: petclinic
    version: updatethis
