apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: 031852407939.dkr.ecr.us-east-1.amazonaws.com/devops-demo
      imagePullSecrets:
        - name: my-docker-credentials
